const KEYWORDS = [
  'select',
  'from',
  'where',
  'group',
  'by',
  'having',
  'order',
  'limit',
  'offset',
  'fetch',
  'top',
  'as',
  'and',
  'or',
  'not',
  'null',
  'is',
  'in',
  'like',
  'ilike',
  'rlike',
  'regexp',
  'between',
  'case',
  'when',
  'then',
  'else',
  'end',
  'join',
  'inner',
  'left',
  'right',
  'full',
  'outer',
  'cross',
  'lateral',
  'natural',
  'on',
  'using',
  'with',
  'recursive',
  'union',
  'all',
  'any',
  'except',
  'intersect',
  'minus',
  'distinct',
  'qualify',
  'over',
  'partition',
  'window',
  'rows',
  'range',
  'unbounded',
  'preceding',
  'following',
  'current',
  'row',
  'asc',
  'desc',
  'nulls',
  'first',
  'last',
  'true',
  'false',
  'cast',
  'try_cast',
  'exists',
  'values',
  'pivot',
  'unpivot',
  'sample',
  'tablesample',
  'replace',
  'if',
  'table',
  'view',
  'temporary',
  'temp',
  'transient',
  'volatile',
  'secure',
  'insert',
  'into',
  'update',
  'delete',
  'merge',
  'set',
  'flatten',
  'connect',
  'start',
  'prior',
  'javascript',
  'python',
  'java',
  'scala',
  'sql',
  'begin',
  'declare',
  'let',
  'return',
  'call',
  'procedure',
  'function',
  'returns',
  'handler',
  'packages',
  'imports',
  'runtime_version',
  'execute',
  'owner',
  'caller',
  'strict',
  'called',
  'input',
  'output',
  'out',
  'copy',
  'grants',
  'stage',
  'file_format',
  'warehouse',
  'database',
  'schema',
  'stream',
  'task',
  'schedule',
  'after',
  'dynamic',
  'clone',
  'time',
  'travel',
  'at',
  'before',
  'changes',
  'match_recognize',
  'asof',
  'show',
  'describe',
  'grant',
  'revoke',
];

const TYPES = [
  'array',
  'bigint',
  'binary',
  'boolean',
  'char',
  'date',
  'datetime',
  'dec',
  'decimal',
  'double',
  'float',
  'geography',
  'geometry',
  'int',
  'integer',
  'map',
  'number',
  'numeric',
  'object',
  'real',
  'string',
  'text',
  'time',
  'timestamp',
  'timestamp_ltz',
  'timestamp_ntz',
  'timestamp_tz',
  'variant',
  'varchar',
  'vector',
];

const BODY_DELIMITER_RULES = [
  dollarQuotedBody,
];

module.exports = grammar({
  name: 'snowflake',

  extras: $ => [
    /[\s\uFEFF\u2060]+/,
    $.comment,
  ],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat(choice($.create_statement, $.terminator, $._token)),

    // A `CREATE …` statement, structured just enough to associate a `LANGUAGE` clause with the
    // following `$$ … $$` body so an embedded-language injection can target it. Everything else
    // inside stays as flat tokens; only `language_clause` is lifted out. Anchored on dedicated
    // `kw_create`/`kw_language` tokens (highlighted as keywords) because the catch-all `keyword`
    // token can't be constrained to a specific word.
    create_statement: $ => prec.right(seq(
      $.kw_create,
      repeat(choice($.language_clause, $._create_token)),
    )),

    language_clause: $ => seq(
      $.kw_language,
      field('name', choice($.keyword, $.type, $.identifier)),
    ),

    kw_create: _ => token(prec(3, word('create'))),
    kw_language: _ => token(prec(3, word('language'))),

    // The flat tokens allowed inside a CREATE statement (everything but `;`, which ends it).
    _create_token: $ => choice(
      $.stage_reference,
      $.keyword,
      $.type,
      $.dollar_string,
      $.string,
      $.quoted_identifier,
      $.number,
      $.variable,
      $.identifier,
      $.operator,
      $.punctuation,
    ),

    _token: $ => choice(
      $.stage_reference,
      $.keyword,
      $.kw_language,
      $.type,
      $.dollar_string,
      $.string,
      $.quoted_identifier,
      $.number,
      $.variable,
      $.identifier,
      $.operator,
      $.punctuation,
    ),

    terminator: _ => ';',

    comment: _ => token(prec(10, choice(
      seq('--', /[^\r\n]*/),
      seq('//', /[^\r\n]*/),
      seq('/*', repeat(choice(/[^*]/, seq('*', /[^/]/))), repeat('*'), '/'),
    ))),

    stage_reference: _ => token(prec(4, seq(
      '@',
      repeat1(choice(
        /[A-Za-z0-9_$%~./:=+-]+/,
        seq('"', repeat(choice(/[^"]/, '""')), '"'),
      )),
    ))),

    keyword: _ => token(prec(2, choice(...KEYWORDS.map(word)))),

    type: _ => token(prec(2, choice(...TYPES.map(word)))),

    identifier: _ => /[A-Za-z_][A-Za-z0-9_$]*/,

    quoted_identifier: _ => token(seq(
      '"',
      repeat(choice(/[^"]/, '""')),
      '"',
    )),

    string: _ => token(seq(
      "'",
      repeat(choice(/[^'\\]/, /\\./, "''")),
      "'",
    )),

    dollar_string: _ => token(choice(...BODY_DELIMITER_RULES.map(rule => rule()))),

    number: _ => token(choice(
      /\d+\.\d*([eE][+-]?\d+)?/,
      /\.\d+([eE][+-]?\d+)?/,
      /\d+([eE][+-]?\d+)?/,
    )),

    variable: _ => token(seq('$', choice(/[0-9]+/, /[A-Za-z_][A-Za-z0-9_$]*/))),

    operator: _ => token(prec(3, choice(
      '->>',
      '|>',
      '::',
      ':=',
      '=>',
      '->',
      '||',
      '<=>',
      '<=',
      '>=',
      '<>',
      '!=',
      '=',
      '<',
      '>',
      '+',
      '-',
      '*',
      '/',
      '%',
      ':',
      '|',
      '&',
      '^',
      '~',
      '@',
      '?',
      '!',
    ))),

    punctuation: _ => token(choice(
      '(',
      ')',
      '[',
      ']',
      '{',
      '}',
      ',',
      '.',
    )),
  },
});

function word(value) {
  const escaped = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(escaped.replace(/[A-Za-z]/g, char => `[${char.toLowerCase()}${char.toUpperCase()}]`));
}

function dollarQuotedBody() {
  return seq(
    '$$',
    repeat(choice(/[^$]/, seq('$', /[^$]/))),
    '$$',
  );
}
