-- 00_bootstrap.sql
-- Requires a role that can create a database and an X-SMALL warehouse.
CREATE OR REPLACE WAREHOUSE FORMATTER_TEST_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Temporary warehouse for Snowflake formatter E2E tests';

CREATE OR REPLACE DATABASE SNOWFLAKE_FORMATTER_LAB
    COMMENT = 'Disposable multilingual formatter and procedure scenario';

CREATE OR REPLACE SCHEMA SNOWFLAKE_FORMATTER_LAB.RAW;
CREATE OR REPLACE SCHEMA SNOWFLAKE_FORMATTER_LAB.CORE;
CREATE OR REPLACE SCHEMA SNOWFLAKE_FORMATTER_LAB.MART;
CREATE OR REPLACE SCHEMA SNOWFLAKE_FORMATTER_LAB.OPS;
CREATE OR REPLACE SCHEMA SNOWFLAKE_FORMATTER_LAB.UTIL;

USE WAREHOUSE FORMATTER_TEST_WH;
USE DATABASE SNOWFLAKE_FORMATTER_LAB;
USE SCHEMA OPS;

ALTER SESSION SET
    TIMEZONE = 'Asia/Tokyo',
    WEEK_START = 1,
    TIMESTAMP_OUTPUT_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF3 TZH:TZM',
    QUERY_TAG = 'snowflake-formatter-torture-suite/e2e';
