//! Snowflake COPY / object-DDL option key recognition.

/// Whether `word` (case-insensitively) is a canonical Snowflake COPY / object-DDL option key.
///
/// Adding a word here only changes the casing of a recognized key in key position. It never
/// re-spells values, identifiers, or literals.
pub(super) fn is_option_key(word: &str) -> bool {
    OPTION_KEYS
        .binary_search(&word.to_ascii_lowercase().as_str())
        .is_ok()
}

/// A no-value option flag word (`ORDER` / `NOORDER`): a recognized key that stands alone with no
/// `= value`.
pub(super) fn is_option_flag(word: &str) -> bool {
    OPTION_FLAGS
        .binary_search(&word.to_ascii_lowercase().as_str())
        .is_ok()
}

/// Canonical option-key spellings, lower-cased and kept sorted for `binary_search`. Multi-word
/// keys such as `PARTITION BY`, `START WITH`, `CLUSTER BY`, `COPY GRANTS` are recognized via their
/// already-reserved leading keyword and the `WITH`/`BY` connector.
const OPTION_KEYS: &[&str] = &[
    "ai_question_categorization",
    "ai_sql_generation",
    "ai_verified_queries",
    "allow_duplicate",
    "allowed_values",
    "append_only",
    "auto_refresh",
    "auto_resume",
    "auto_suspend",
    "base_location",
    "binary_as_text",
    "binary_format",
    "catalog",
    "change_tracking",
    "classification_profile",
    "comment",
    "compression",
    "config",
    "contact",
    "credentials",
    "data_metric_schedule",
    "data_retention_time_in_days",
    "date_format",
    "default_ddl_collation",
    "detailed_output",
    "directory",
    "disable_auto_convert",
    "empty_field_as_null",
    "enable",
    "enable_octal",
    "enable_query_acceleration",
    "enable_schema_evolution",
    "encoding",
    "encryption",
    "enforce_length",
    "error_integration",
    "error_on_column_count_mismatch",
    "escape",
    "escape_unenclosed_field",
    "event_table",
    "execute_as",
    "exempt_other_policies",
    "external_table_auto_refresh",
    "external_volume",
    "field_delimiter",
    "field_optionally_enclosed_by",
    "file_extension",
    "file_format",
    "files",
    "finalize",
    "force",
    "format_name",
    "ignore_utf8_errors",
    "include_metadata",
    "include_query_id",
    "increment",
    "initialize",
    "initially_suspended",
    "insert_only",
    "log_level",
    "master_key",
    "match_by_column_name",
    "max_cluster_count",
    "max_concurrency_level",
    "max_data_extension_time_in_days",
    "max_file_size",
    "min_cluster_count",
    "multi_line",
    "null_if",
    "on_error",
    "overlap_policy",
    "overwrite",
    "parse_header",
    "pattern",
    "pipe_execution_paused",
    "preserve_space",
    "propagate",
    "purge",
    "query_acceleration_max_scale_factor",
    "record_delimiter",
    "refresh_mode",
    "refresh_on_create",
    "replace_invalid_characters",
    "resource_constraint",
    "resource_monitor",
    "return_failed_only",
    "runtime_version",
    "scaling_policy",
    "schedule",
    "serverless_task_max_statement_size",
    "serverless_task_min_statement_size",
    "show_initial_rows",
    "single",
    "size_limit",
    "skip_blank_lines",
    "skip_byte_order_mark",
    "skip_header",
    "snappy_compression",
    "start",
    "statement_queued_timeout_in_seconds",
    "statement_timeout_in_seconds",
    "storage_integration",
    "strip_null_values",
    "strip_outer_array",
    "strip_outer_element",
    "suspend_task_after_num_failures",
    "target_completion_interval",
    "target_lag",
    "task_auto_retry_attempts",
    "time_format",
    "timestamp_format",
    "trace_level",
    "trim_space",
    "truncatecolumns",
    "type",
    "url",
    "use_logical_type",
    "use_vectorized_scanner",
    "user_task_managed_initial_warehouse_size",
    "user_task_minimum_trigger_interval_in_seconds",
    "user_task_timeout_ms",
    "validation_mode",
    "warehouse",
    "warehouse_size",
    "warehouse_type",
];

/// No-value option flag words, lower-cased and kept sorted.
const OPTION_FLAGS: &[&str] = &["noorder", "order"];
